// Generated by kea-typegen on Thu, 26 Jun 2025 13:26:32 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { Job } from '../types'

export interface jobsLogicType extends Logic {
    actionCreators: {
        loadJobs: () => ({
            type: "load jobs (src.logic.jobsLogic)";
            payload: any;
        });
        loadJobsSuccess: (jobs: any, payload?: any) => ({
            type: "load jobs success (src.logic.jobsLogic)";
            payload: {
                jobs: any;
                payload?: any;
            };
        });
        loadJobsFailure: (error: string, errorObject?: any) => ({
            type: "load jobs failure (src.logic.jobsLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
        loadJob: (id: string) => ({
            type: "load job (src.logic.jobsLogic)";
            payload: string;
        });
        loadJobSuccess: (job: any, payload?: string) => ({
            type: "load job success (src.logic.jobsLogic)";
            payload: {
                job: any;
                payload?: string;
            };
        });
        loadJobFailure: (error: string, errorObject?: any) => ({
            type: "load job failure (src.logic.jobsLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
        addJob: (job: Job) => ({
            type: "add job (src.logic.jobsLogic)";
            payload: {
                job: Job;
            };
        });
        updateJob: (job: Job) => ({
            type: "update job (src.logic.jobsLogic)";
            payload: {
                job: Job;
            };
        });
        deleteJob: (jobId: string) => ({
            type: "delete job (src.logic.jobsLogic)";
            payload: {
                jobId: string;
            };
        });
    };
    actionKeys: {
        "load jobs (src.logic.jobsLogic)": "loadJobs";
        "load jobs success (src.logic.jobsLogic)": "loadJobsSuccess";
        "load jobs failure (src.logic.jobsLogic)": "loadJobsFailure";
        "load job (src.logic.jobsLogic)": "loadJob";
        "load job success (src.logic.jobsLogic)": "loadJobSuccess";
        "load job failure (src.logic.jobsLogic)": "loadJobFailure";
        "add job (src.logic.jobsLogic)": "addJob";
        "update job (src.logic.jobsLogic)": "updateJob";
        "delete job (src.logic.jobsLogic)": "deleteJob";
    };
    actionTypes: {
        loadJobs: "load jobs (src.logic.jobsLogic)";
        loadJobsSuccess: "load jobs success (src.logic.jobsLogic)";
        loadJobsFailure: "load jobs failure (src.logic.jobsLogic)";
        loadJob: "load job (src.logic.jobsLogic)";
        loadJobSuccess: "load job success (src.logic.jobsLogic)";
        loadJobFailure: "load job failure (src.logic.jobsLogic)";
        addJob: "add job (src.logic.jobsLogic)";
        updateJob: "update job (src.logic.jobsLogic)";
        deleteJob: "delete job (src.logic.jobsLogic)";
    };
    actions: {
        loadJobs: () => void;
        loadJobsSuccess: (jobs: any, payload?: any) => void;
        loadJobsFailure: (error: string, errorObject?: any) => void;
        loadJob: (id: string) => void;
        loadJobSuccess: (job: any, payload?: string) => void;
        loadJobFailure: (error: string, errorObject?: any) => void;
        addJob: (job: Job) => void;
        updateJob: (job: Job) => void;
        deleteJob: (jobId: string) => void;
    };
    asyncActions: {
        loadJobs: () => Promise<any>;
        loadJobsSuccess: (jobs: any, payload?: any) => Promise<any>;
        loadJobsFailure: (error: string, errorObject?: any) => Promise<any>;
        loadJob: (id: string) => Promise<any>;
        loadJobSuccess: (job: any, payload?: string) => Promise<any>;
        loadJobFailure: (error: string, errorObject?: any) => Promise<any>;
        addJob: (job: Job) => Promise<any>;
        updateJob: (job: Job) => Promise<any>;
        deleteJob: (jobId: string) => Promise<any>;
    };
    defaults: {
        jobs: any;
        jobsLoading: boolean;
        job: any;
        jobLoading: boolean;
    };
    events: {};
    key: undefined;
    listeners: {
        "addJob": ((action: {
            type: "add job (src.logic.jobsLogic)";
            payload: {
                job: Job;
            };
        }, previousState: any) => void | Promise<void>)[];
        "updateJob": ((action: {
            type: "update job (src.logic.jobsLogic)";
            payload: {
                job: Job;
            };
        }, previousState: any) => void | Promise<void>)[];
        "deleteJob": ((action: {
            type: "delete job (src.logic.jobsLogic)";
            payload: {
                jobId: string;
            };
        }, previousState: any) => void | Promise<void>)[];
    };
    path: [
        "src",
        "logic",
        "jobsLogic"
    ];
    pathString: "src.logic.jobsLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        jobs: any;
        jobsLoading: boolean;
        job: any;
        jobLoading: boolean;
    };
    reducers: {
        jobs: (state: any, action: any, fullState: any) => any;
        jobsLoading: (state: boolean, action: any, fullState: any) => boolean;
        job: (state: any, action: any, fullState: any) => any;
        jobLoading: (state: boolean, action: any, fullState: any) => boolean;
    };
    selector: (state: any) => {
        jobs: any;
        jobsLoading: boolean;
        job: any;
        jobLoading: boolean;
    };
    selectors: {
        jobs: (state: any, props?: any) => any;
        jobsLoading: (state: any, props?: any) => boolean;
        job: (state: any, props?: any) => any;
        jobLoading: (state: any, props?: any) => boolean;
    };
    sharedListeners: {};
    values: {
        jobs: any;
        jobsLoading: boolean;
        job: any;
        jobLoading: boolean;
    };
    _isKea: true;
    _isKeaWithKey: false;
}