// Generated by kea-typegen on Fri, 27 Jun 2025 09:26:37 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

export interface routerLogicType extends Logic {
    actionCreators: {
        goToHome: () => ({
            type: "go to home (src.logic.routerLogic)";
            payload: {
                value: true;
            };
        });
        goToJobs: () => ({
            type: "go to jobs (src.logic.routerLogic)";
            payload: {
                value: true;
            };
        });
        goToAddJob: () => ({
            type: "go to add job (src.logic.routerLogic)";
            payload: {
                value: true;
            };
        });
        goToJob: (id: any) => ({
            type: "go to job (src.logic.routerLogic)";
            payload: {
                id: any;
            };
        });
        goToEditJob: (id: any) => ({
            type: "go to edit job (src.logic.routerLogic)";
            payload: {
                id: any;
            };
        });
    };
    actionKeys: {
        "go to home (src.logic.routerLogic)": "goToHome";
        "go to jobs (src.logic.routerLogic)": "goToJobs";
        "go to add job (src.logic.routerLogic)": "goToAddJob";
        "go to job (src.logic.routerLogic)": "goToJob";
        "go to edit job (src.logic.routerLogic)": "goToEditJob";
    };
    actionTypes: {
        goToHome: "go to home (src.logic.routerLogic)";
        goToJobs: "go to jobs (src.logic.routerLogic)";
        goToAddJob: "go to add job (src.logic.routerLogic)";
        goToJob: "go to job (src.logic.routerLogic)";
        goToEditJob: "go to edit job (src.logic.routerLogic)";
    };
    actions: {
        goToHome: () => void;
        goToJobs: () => void;
        goToAddJob: () => void;
        goToJob: (id: any) => void;
        goToEditJob: (id: any) => void;
    };
    asyncActions: {
        goToHome: () => Promise<any>;
        goToJobs: () => Promise<any>;
        goToAddJob: () => Promise<any>;
        goToJob: (id: any) => Promise<any>;
        goToEditJob: (id: any) => Promise<any>;
    };
    defaults: {};
    events: {};
    key: undefined;
    listeners: {};
    path: [
        "src",
        "logic",
        "routerLogic"
    ];
    pathString: "src.logic.routerLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {};
    reducers: {};
    selector: (state: any) => {};
    selectors: {};
    sharedListeners: {};
    values: {};
    _isKea: true;
    _isKeaWithKey: false;
}