// Generated by kea-typegen on Fri, 27 Jun 2025 09:35:08 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { SceneParams } from './sceneLogic'

export interface sceneLogicType extends Logic {
    actionCreators: {
        setScene: (scene: any, params?: any) => ({
            type: "set scene (src.logic.sceneLogic)";
            payload: {
                params: any;
                scene: any;
            };
        });
    };
    actionKeys: {
        "set scene (src.logic.sceneLogic)": "setScene";
    };
    actionTypes: {
        setScene: "set scene (src.logic.sceneLogic)";
    };
    actions: {
        setScene: (scene: any, params?: any) => void;
    };
    asyncActions: {
        setScene: (scene: any, params?: any) => Promise<any>;
    };
    defaults: {
        scene: string;
        params: SceneParams;
    };
    events: {};
    key: undefined;
    listeners: {};
    path: [
        "src",
        "logic",
        "sceneLogic"
    ];
    pathString: "src.logic.sceneLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        scene: string;
        params: SceneParams;
    };
    reducers: {
        scene: (state: string, action: any, fullState: any) => string;
        params: (state: SceneParams, action: any, fullState: any) => SceneParams;
    };
    selector: (state: any) => {
        scene: string;
        params: SceneParams;
    };
    selectors: {
        scene: (state: any, props?: any) => string;
        params: (state: any, props?: any) => SceneParams;
    };
    sharedListeners: {};
    values: {
        scene: string;
        params: SceneParams;
    };
    _isKea: true;
    _isKeaWithKey: false;
}